version: '3.7'

networks:
  back-tier:

services:
  metabase:
    image: metabase/metabase:latest
    volumes:
      - ./.volumes/metabase:/metabase-data
      - ./plugins:/plugins
      - ./certs:/usr/local/share/ca-certificates
    ports:
      - 3000:3000
    environment:
      MB_SITE_URL: http://localhost:3000/metabase/
      MB_DB_FILE: /metabase-data/metabase.db
