apiVersion: v1
kind: Namespace
metadata:
  name: metabase
---
apiVersion: v1
kind: Service
metadata:
  name: metabase-server
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:083054810114:certificate/b735f978-c69e-4987-94b4-79c425686a3c
  namespace: metabase
  labels:
    app: metabase-server
spec:
  type: LoadBalancer
  ports:
  # Remove not secure connections and
  # only allow SSL.
  - name: http
    port: 80
    targetPort: 3000
  # - name: https
  #   port: 443
  #   targetPort: 3000
  selector:
    app: metabase-server
  loadBalancerSourceRanges:
  - 179.191.171.144/32  # VPN Azion - BR
  - 34.227.40.48/32     # VPN Azion - US
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase-server
  namespace: metabase
  labels:
    app: metabase-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase-server
  template:
    metadata:
      labels:
        app: metabase-server
    spec:
      containers:
        - name: metabase-server
          image: 083054810114.dkr.ecr.us-east-1.amazonaws.com/azion-metabase:7.1.3-1
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
